FROM UPSTREAM_REPO

ARG MAILHOG_VERSION=0.2.1
ENV MAILHOG_VERSION=$MAILHOG_VERSION

ENV MH_SMTP_BIND_ADDR 127.0.0.1:1025

ENV PHP_INI /etc/php/7.0/fpm/php.ini

ENV NGINX_SITE_TEMPLATE /etc/nginx/nginx-site.conf
ENV NGINX_DOCROOT /var/www/html
# Defines vars in colon-separated notation to be subsituted with values for NGINX_SITE_TEMPLATE on start
ENV NGINX_SITE_VARS '$NGINX_DOCROOT'

RUN apt-get update && \
    apt-get install --no-install-recommends --no-install-suggests -y \
        iputils-ping telnet netcat6 iproute2 vim nano php7.0-xdebug gettext && \
    apt-get autoremove -y && \
    apt-get clean -y && \
	rm -rf /var/lib/apt/lists/*

ADD https://github.com/mailhog/MailHog/releases/download/v${MAILHOG_VERSION}/MailHog_linux_amd64 /usr/bin/mailhog

RUN chmod ugo+x /usr/bin/mailhog && \
    rm /etc/nginx/sites-enabled/default.conf /etc/nginx/sites-available/default.conf && \
    ln -s /etc/nginx/sites-available/nginx-site.conf /etc/nginx/sites-enabled/nginx-site.conf

ADD files /

VOLUME /var/log/nginx
EXPOSE 443 80 8025
HEALTHCHECK CMD curl --fail http://localhost/healthcheck/ || exit 1
