FROM bitnami/minideb:jessie

ENV PHP_VERSION=5.6
ENV PHP_PREFIX=php${PHP_VERSION}
ENV PHP_EXACTVERSION=5.6.32-1+0~20171027135825.7+jessie~1.gbpd60169
ENV PHP_XDEBUG_VERSION=2.5.5-1+0~20170628201550.1+jessie~1.gbp5a1f48
ENV NGINX_VERSION=1.12.1-1~jessie
ENV DRUSH_VERSION=7.4.0
ENV WP_CLI_VERSION=1.4.0
ENV MAILHOG_VERSION=1.0.0

ENV DEBIAN_FRONTEND noninteractive
ENV TERM xterm
ENV MH_SMTP_BIND_ADDR 127.0.0.1:1025
ENV PHP_INI /etc/php/${PHP_VERSION}/fpm/php.ini
ENV PATH="/root/.composer/vendor/bin:$PATH"
ENV NGINX_SITE_TEMPLATE /etc/nginx/nginx-site.conf
ENV NGINX_DOCROOT /var/www/html
# Defines vars in colon-separated notation to be subsituted with values for NGINX_SITE_TEMPLATE on start
ENV NGINX_SITE_VARS '$NGINX_DOCROOT'

RUN apt-get -qq update && \
	apt-get -qq install --no-install-recommends --no-install-suggests -y \
        procps \
        curl \
        ca-certificates \
        apt-transport-https \
        wget && \
    wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg && \
    echo "deb https://packages.sury.org/php/ jessie main" > /etc/apt/sources.list.d/php.list && \
    wget -q -O /tmp/nginx_signing.key http://nginx.org/keys/nginx_signing.key && \
    apt-key add /tmp/nginx_signing.key && \
    echo "deb http://nginx.org/packages/debian/ jessie nginx" >> /etc/apt/sources.list && \
	apt-get -qq update && \
	apt-get -qq install --no-install-recommends --no-install-suggests -y \
        less \
        git \
        mysql-client \
        nginx \
        libcap2-bin \
        supervisor \
        sudo \
        imagemagick \
        iputils-ping \
        telnet \
        netcat6 \
        iproute2 \
		vim \
		nano \
		gettext \
		ncurses-bin \
		zip \
		unzip \
		libpcre3 \
        ${PHP_PREFIX}-curl=${PHP_EXACTVERSION} \
        ${PHP_PREFIX}-cgi=${PHP_EXACTVERSION} \
        ${PHP_PREFIX}-cli=${PHP_EXACTVERSION} \
        ${PHP_PREFIX}-common=${PHP_EXACTVERSION} \
        ${PHP_PREFIX}-fpm=${PHP_EXACTVERSION} \
        ${PHP_PREFIX}-gd=${PHP_EXACTVERSION} \
        ${PHP_PREFIX}-json=${PHP_EXACTVERSION} \
        ${PHP_PREFIX}-mysql=${PHP_EXACTVERSION} \
        ${PHP_PREFIX}-mbstring=${PHP_EXACTVERSION} \
        ${PHP_PREFIX}-xml=${PHP_EXACTVERSION} \
        ${PHP_PREFIX}-xmlrpc=${PHP_EXACTVERSION} \
        ${PHP_PREFIX}-mcrypt=${PHP_EXACTVERSION} \
        ${PHP_PREFIX}-opcache=${PHP_EXACTVERSION} \
        ${PHP_PREFIX}-soap=${PHP_EXACTVERSION} \
        ${PHP_PREFIX}-readline=${PHP_EXACTVERSION} \
        ${PHP_PREFIX}-zip=${PHP_EXACTVERSION} \
        php-xdebug=${PHP_XDEBUG_VERSION} && \
    apt-get -qq autoremove -y && \
    apt-get -qq clean -y && \
	rm -rf /var/lib/apt/lists/* && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

ADD "https://github.com/mailhog/MailHog/releases/download/v${MAILHOG_VERSION}/MailHog_linux_amd64" /usr/local/bin/mailhog
ADD "https://github.com/wp-cli/wp-cli/releases/download/v${WP_CLI_VERSION}/wp-cli-${WP_CLI_VERSION}.phar" /usr/local/bin/wp-cli
ADD files /

RUN composer global require drush/drush:${DRUSH_VERSION} && ln -s /root/.composer/vendor/bin/drush /usr/local/bin/drush

RUN rm -f /etc/php/${PHP_VERSION}/cli/php.ini && \
    ln -s /etc/php/{PHP_VERSION}/fpm/php.ini /etc/php/${PHP_VERSION}/cli/php.ini && \
    mkdir -p /etc/nginx/sites-enabled && \
    touch /var/log/php-fpm.log && \
    chown nginx:nginx /var/log/php-fpm.log && \
    chown -R nginx:nginx /var/run && \
    touch /var/log/nginx/access.log && \
    touch /var/log/nginx/error.log && \
    chown -R nginx:nginx /var/log/nginx/ && \
    mkdir -p /var/lib/nginx/logs && \
    touch /var/lib/nginx/logs/error.log && \
    chown nginx:nginx /var/lib/nginx/logs/error.log && \
    chmod ugo+x /usr/local/bin/* && \
    chmod ugo+x /start.sh

VOLUME /var/log/nginx
EXPOSE 443 80 8025
HEALTHCHECK --interval=5s --retries=5 CMD curl --fail http://localhost/healthcheck/ || exit 1
CMD ["/start.sh"]
